### ISSUE TITLE
Sidebar module

### ISSUE THREAD

**Issue by sharlagelfand** [purposeanalytics/lemur#16]
Keeping track of all the TODOs/issues for the sidebar module

- [x] Show city wide data by default -> w/ inputs to change / filter data (#11)
- [x] Show building / neighbourhood data when zoomed -> w/ inputs to change / filter data (#12)
- ~Download data shown (#13)~ move to the data & definitions page
- [x] Descriptive language and alt text for charts (#14)
- [x] Single-page export for data shown (report moreso than actual data) -> should have PDF and HTML option for accessibility (#15)
