### ISSUE TITLE
Main map module

### ISSUE THREAD

**Issue by sharlagelfand** [purposeanalytics/lemur#5]
Just keeping track of all the TODOs/issues related to the main map module here

- [x] Map itself (#6)
- [x] Address search (data: #1, module: #3)
- [x] Neighbourhood selection (data: #2, module: #4)
- [ ] ~Update neighbourhoods data (#23)~
- [x] Zoom map to address/neighbourhood selected (#7)
- [x] Tooltip with building info (#8)
- [x] Map layers (#10)
- [x] Select building/neighbourhood by clicking on map (#9)
